apiVersion: v1
kind: Service
metadata:
  name: email-service
  labels:
    app: email-app
spec:
  type: ClusterIP
  selector:
    app: email-app
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
