apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: email-service
build:
  artifacts:
    - image: miguelrojas/email-service
      buildpacks:
        builder: gcr.io/paketo-buildpacks/builder:base
        env:
          - BP_JVM_VERSION=11.*
deploy:
  helm:
    releases:
      - name: polardb-emailnotifications
        remoteChart: bitnami/postgresql
        setValues:
          postgresqlUsername: admin
          postgresqlPassword: admin
          postgresqlDatabase: polardb_order
          image.tag: 13
          service.port: 5433
  kubectl:
    manifests:
      - k8s/*.yml
