apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: subscription-service
build:
  artifacts:
    - image: miguelrojas/subscription-service
      buildpacks:
        builder: gcr.io/paketo-buildpacks/builder:base
        env:
          - BP_JVM_VERSION=11.*
deploy:
  helm:
    releases:
      - name: polardb-catalog
        remoteChart: bitnami/postgresql
        setValues:
          postgresqlUsername: admin
          postgresqlPassword: admin
          postgresqlDatabase: polardb_catalog
          image.tag: 13
  kubectl:
    manifests:
      - k8s/*.yml
