apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription-app
  labels:
    app: subscription-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscription-app
  template:
    metadata:
      labels:
        app: subscription-app
    spec:
      terminationGracePeriodSeconds: 20
      containers:
        - name: subscription-app
          image: miguelrojas/subscription-service:0.0.1-SNAPSHOT
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9001
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://polardb-catalog-postgresql:5432/polardb_catalog
          resources:
            requests:
              memory: "756Mi"
              cpu: "0.5"
            limits:
              memory: "756Mi"
