apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-app
  labels:
    app: email-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-app
  template:
    metadata:
      labels:
        app: email-app
    spec:
      terminationGracePeriodSeconds: 20
      containers:
        - name: catalog-app
          image: miguelrojas/email-service:0.0.1-SNAPSHOT
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9002
          env:
            - name: SPRING_DATASOURCE_URL
              value: r2dbc:postgresql://polardb-emailnotifications-postgresql:5432/polardb_order
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.5"
            limits:
              memory: "512Mi"
