apiVersion: v1
kind: Service
metadata:
  name: emailnotifications-service
  labels:
    app: emailnotifications-app
spec:
  type: ClusterIP
  selector:
    app: emailnotifications-app
  ports:
  - protocol: TCP
    port: 9002
    targetPort: 9002
